[package]
name = "kafka-client"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-lite = "2.6.0"
glommio = "0.9.0"
kafka-protocol = { version = "0.15.0", features = ["messages_enums"] }
bytes = "1.10.1"
futures = "0.3.31"
murmur2 = "0.1.0"
rand = "0.9.1"
futures-io = "0.3.31"
